name: Code Quality Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Instalar dependências
      run: |
        go mod tidy
        go mod download

    - name: Verificar formatação (gofmt)
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "⚠️ Código mal formatado. Rode 'gofmt -w .' para corrigir.";
          exit 1;
        fi

    - name: Instalar golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

    - name: Rodar golangci-lint
      run: |
        $(go env GOPATH)/bin/golangci-lint run ./...

    - name: Rodar testes com cobertura
      run: go test ./... -v -coverprofile=coverage.out

    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: cobertura-de-testes
        path: coverage.out
